//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CILSegmentText_H_
#define CILSegmentText_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CInstrumentLabPkgRAD_H_
  #include <CInstrumentLabPkgRAD.h>
#endif
#ifndef CILBasicInstrument_H_
  #include <CILBasicInstrument.h>
#endif
#ifndef CULBasicControl_H_
  #include <CULBasicControl.h>
#endif
#ifndef CILSegmentIndicator_H_
  #include <CILSegmentIndicator.h>
#endif
#ifndef CSLControlCollection_H_
  #include <CSLControlCollection.h>
#endif
#ifndef CSLStreamTypes_H_
  #include <CSLStreamTypes.h>
#endif
#ifndef CSLComponentCollection_H_
  #include <CSLComponentCollection.h>
#endif
#ifndef CLPComponent_H_
  #include <CLPComponent.h>
#endif
//------------------------------------------------------------------------------




//------------------------------------------------------------------------------
class CTILSegmentText : public CTILCustomizableSegmentIndicator
{
//DOM-IGNORE-BEGIN
  typedef CTILCustomizableSegmentIndicator inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWInputPinProperty InputPin;

public:    // Class Properties
  class CTLPComponentElements &Elements;

public:    // Properties
  CLPEnumProperty<CTILSegmentsType> SegmentsType;
  CLPProperty<unsigned int> Rows;
  CLPProperty<unsigned int> Cols;
  CLPProperty<CTString> Text;

public:

public:
  virtual void Open( HWND hParent );
  virtual void Open( CLPControl &Parent );

public:
  CTILSegmentText( HWND hParent );
  CTILSegmentText();
  virtual ~CTILSegmentText();
};
//------------------------------------------------------------------------------
class CTILSegmentTextLayer : public CTILSegmentText
{
//DOM-IGNORE-BEGIN
  typedef CTILSegmentText inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:
  virtual void Open( HWND hParent );
  virtual void Open( CLPControl &Parent );

public:
  CTILSegmentTextLayer( HWND hParent );
  CTILSegmentTextLayer();
};
//------------------------------------------------------------------------------
class CTILExternalSegmentTextElement : public CTILSegmentText
{
//DOM-IGNORE-BEGIN
  typedef CTILSegmentText inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // Class Properties
  class CTULElementOffsets &Position;
  class CTULElement2DSize &Size;

public:

public:
  virtual void Open( HWND hParent );
  virtual void Open( CLPControl &Parent );

public:
  CTILExternalSegmentTextElement( HWND hParent );
  CTILExternalSegmentTextElement();
  virtual ~CTILExternalSegmentTextElement();
};
//------------------------------------------------------------------------------
class CTILExternalSegmentTextMatrixLayer : public CTILExternalSegmentTextElement
{
//DOM-IGNORE-BEGIN
  typedef CTILExternalSegmentTextElement inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:
  virtual void Open( HWND hParent );
  virtual void Open( CLPControl &Parent );

public:
  CTILExternalSegmentTextMatrixLayer( HWND hParent );
  CTILExternalSegmentTextMatrixLayer();
};
//------------------------------------------------------------------------------
#include <CILSegmentTextCode.h>
//------------------------------------------------------------------------------
#endif   // CILSegmentText_H_
//------------------------------------------------------------------------------
