//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLBasicGenericComplex_H_
#define CSLBasicGenericComplex_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgRAD_H_
  #include <CSignalLabBasicPkgRAD.h>
#endif
#ifndef CSLCommonFilter_H_
  #include <CSLCommonFilter.h>
#endif
#ifndef CSLGenericFilterTypes_H_
  #include <CSLGenericFilterTypes.h>
#endif
#ifndef CLPComponent_H_
  #include <CLPComponent.h>
#endif
//------------------------------------------------------------------------------




//------------------------------------------------------------------------------
class CTSLBasicGenericComplex : public CTSLCommonComplexFilter
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonComplexFilter inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // Events
//  void __stdcall OnStop(VCLHANDLE Sender);
  CLPEventProperty_1<0, void, VCLHANDLE> OnStop;

public:    // Properties
  CLPEnumProperty<CTSLSynchronizeType> SynchronizeType;

public:
  void SendStartCommand( double ARate );
  void SendStopCommand();
  void ClearQueue();

public:
  CTSLBasicGenericComplex();
};
//------------------------------------------------------------------------------
class CTSLBasicStartGenericComplex : public CTSLBasicGenericComplex
{
//DOM-IGNORE-BEGIN
  typedef CTSLBasicGenericComplex inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // Events
//  void __stdcall OnStart(VCLHANDLE Sender, double SampleRate);
  CLPEventProperty_2<1, void, VCLHANDLE, double> OnStart;

public:
  CTSLBasicStartGenericComplex();
};
//------------------------------------------------------------------------------
#include <CSLBasicGenericComplexCode.h>
//------------------------------------------------------------------------------
#endif   // CSLBasicGenericComplex_H_
//------------------------------------------------------------------------------
