//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLChangeRangeCode_H_
#define CSLChangeRangeCode_H_

#pragma optimize( "", off )
//------------------------------------------------------------------------------
inline CTSLChangeRange::CTSLChangeRange() :
  Max( GetInstance(), _T( "Max" ) ),
  Min( GetInstance(), _T( "Min" ) ),
  InputPin( GetInstance(), _T( "InputPin" ) ),
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = ::Get_SignalLabAdditionalPkgRAD();
  CLPComponent::OpenComponent( _T( "TSLChangeRange" ) );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLChangeRange::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#pragma optimize( "", on )
#endif   // CSLChangeRangeCode_H_
//------------------------------------------------------------------------------
