//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLGenericFilterTypes_H_
#define CSLGenericFilterTypes_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabBasicPkgRAD_H_
  #include <CSignalLabBasicPkgRAD.h>
#endif
//------------------------------------------------------------------------------




//------------------------------------------------------------------------------
#include <CSLGenericFilterTypesCode.h>
//------------------------------------------------------------------------------
#endif   // CSLGenericFilterTypes_H_
//------------------------------------------------------------------------------
