//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLGenericFilterTypesCode_H_
#define CSLGenericFilterTypesCode_H_

#pragma optimize( "", off )
//------------------------------------------------------------------------------
#pragma optimize( "", on )
#endif   // CSLGenericFilterTypesCode_H_
//------------------------------------------------------------------------------
