//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLGenericRealValueGen_H_
#define CSLGenericRealValueGen_H_

//------------------------------------------------------------------------------
#ifndef VCLSupportH
  #include <VCLSupport.h>
#endif

#ifndef CSignalLabAdditionalPkgRAD_H_
  #include <CSignalLabAdditionalPkgRAD.h>
#endif
#ifndef CSLCommonGen_H_
  #include <CSLCommonGen.h>
#endif
//------------------------------------------------------------------------------




//------------------------------------------------------------------------------
class CTSLGenericRealValueGen : public CTSLCommonGen
{
//DOM-IGNORE-BEGIN
  typedef CTSLCommonGen inherited;
//DOM-IGNORE-END

  VCLHANDLE LibraryHandle;

protected:
  virtual TLPFunctionEntry  GetFunction( const char *function_name );

public:    // OpenWire Pins
  CTOWOutputPinProperty OutputPin;

public:    // Events
//  void __stdcall OnGenerate(VCLHANDLE Sender, double & OutValue, bool & Populated, bool & Finished);
  CLPEventProperty_4<0, void, VCLHANDLE, double &, bool &, bool &> OnGenerate;

public:
  CTSLGenericRealValueGen();
};
//------------------------------------------------------------------------------
#include <CSLGenericRealValueGenCode.h>
//------------------------------------------------------------------------------
#endif   // CSLGenericRealValueGen_H_
//------------------------------------------------------------------------------
