//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLGenericRealValueGenCode_H_
#define CSLGenericRealValueGenCode_H_

#pragma optimize( "", off )
//------------------------------------------------------------------------------
inline CTSLGenericRealValueGen::CTSLGenericRealValueGen() :
  OutputPin( GetInstance(), _T( "OutputPin" ) ),
  OnGenerate( GetInstance(), _T( "OnGenerate" ) )
{
  LibraryHandle = ::Get_SignalLabAdditionalPkgRAD();
  CLPComponent::OpenComponent( _T( "TSLGenericRealValueGen" ) );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLGenericRealValueGen::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#pragma optimize( "", on )
#endif   // CSLGenericRealValueGenCode_H_
//------------------------------------------------------------------------------
