//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLMultiInputCode_H_
#define CSLMultiInputCode_H_

#pragma optimize( "", off )
//------------------------------------------------------------------------------
inline CTSLMultiInput::CTSLMultiInput() :
  BufferSize( GetInstance(), _T( "BufferSize" ) )
{
  LibraryHandle = Get_SignalLabBasicPkgRAD();
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLMultiInput::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline CTSLRealMultiInput::CTSLRealMultiInput() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = Get_SignalLabBasicPkgRAD();
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLRealMultiInput::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
inline CTSLComplexMultiInput::CTSLComplexMultiInput() :
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = Get_SignalLabBasicPkgRAD();
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLComplexMultiInput::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
#pragma optimize( "", on )
#endif   // CSLMultiInputCode_H_
//------------------------------------------------------------------------------
