//------------------------------------------------------------------------------
//
//                   Generated by VCL C++/C#.NET FrontEnd.
//                   (C)Copyright Boian Mitov 2005 - 2011
//                              www.mitov.com
//
//------------------------------------------------------------------------------

#ifndef CSLPairCode_H_
#define CSLPairCode_H_

#pragma optimize( "", off )
//------------------------------------------------------------------------------
inline CTSLPair::CTSLPair() :
  InputPins( GetInstance(), _T( "InputPins" ) ),
  OutputPin( GetInstance(), _T( "OutputPin" ) )
{
  LibraryHandle = ::Get_SignalLabBasicPkgRAD();
  CLPComponent::OpenComponent( _T( "TSLPair" ) );
}
//------------------------------------------------------------------------------
inline TLPFunctionEntry CTSLPair::GetFunction( const char *function_name )
{
  TLPFunctionEntry Result = VCL_GetFunction( LibraryHandle, function_name );
  if( Result )
    return Result;

  return inherited::GetFunction( function_name );
}
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
#pragma optimize( "", on )
#endif   // CSLPairCode_H_
//------------------------------------------------------------------------------
